# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=250)),
                ('LastName', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LikeDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostTitle', models.CharField(max_length=250)),
                ('PostDate', models.DateTimeField(verbose_name='Post Date')),
                ('PostImageURL', models.URLField(max_length=250)),
                ('PostText', models.TextField()),
                ('PostVisible', models.BooleanField(default=False)),
                ('GuestUserKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.GuestUser')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='PostKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='GuestUserKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.GuestUser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='PostKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
